repository:

  url: https://bitbucket.company.net/scm/net/web-adc-configurations.git

  branch: master

  local_path: repository

bigip:

  username: admin

instances:

  prod-bigip01:

      host: 10.10.10.11

  prod-bigip02:

      host: 10.10.10.12
